djproject/djproject/urls.py
#from django.urls import include, path
from django.conf.urls import url, include
#from django.urls import path
from django.contrib import admin
#from simpleapp1.admin import admin_site
#from simpleapp1 import views

urlpatterns = [
    url(r'^admin/', admin.site.urls), # required to overcome NoReverseMatch found error
    url(r'^autoscale/', include('simpleapp1.urls')),
#     url(r'^$', views.index, name='index'),
#     url(r'^cpuload/', views.overload_cpu, name='overload_cpu'),
#     url(r'^killpid/(?P<procid>[0-9]+)/$',views.kill_load,name='kill_load'),
    #url(r'^business/', views.business, name='business'),
]

djproject/simpleapp1/urls.py
from django.conf.urls import url
#from django.urls import path
from django.contrib import admin
from simpleapp1 import views
#from simpleapp1.admin import admin_site

app_name = 'simpleapp1'
urlpatterns = [
    url(r'^admin/', admin.site.urls, name="admin"),    
    url(r'^$', views.index, name='index'),
    #url('', views.index, name='index'),
    url(r'^cpuload/', views.overload_cpu, name='overload_cpu'),
    url(r'^killpid/(?P<procid>[0-9]+)/$',views.kill_load,name='kill_load'),
    url(r'^inventory/$', views.Inventory.as_view(), name='inventory'),
    url(r'^inventory/add/$', views.InventoryAdd.as_view(), name='inventory_add'),
    url(r'^inventory/update/(?P<pk>[\w-]+)$', views.InventoryUpdate.as_view(), name='inventory_update'),
    url(r'^openstack/', views.openstack_view, name='openstack'),
    url(r'^osauth/$', views.OSauth.as_view(), name='osauth'),
    url(r'^osauth/add/$', views.OSauthAdd.as_view(), name='osauth_add'),
    url(r'^osauth/update(?P<pk>[\w-]+)$', views.OSauthUpdate.as_view(), name='osauth_update'),
    url(r'^openstackgraph/', views.openstack_graph_view, name='openstackgraph'),
    
    
    #url(r'^business/', views.business, name='business'),
]

djproject/simpleapp1/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from fernet_fields import EncryptedCharField
# Create your models here.

class Laptop(models.Model):
    laptopmodel=models.CharField(max_length=100)
    currentstock=models.CharField(max_length=100)
    totalstock=models.CharField(max_length=100)      
    def __unicode__(self):
        return self.laptopmodel
    


class Order(models.Model):
    ordernum=models.CharField(max_length=100)
    qty=models.CharField(max_length=16)
    laptop=models.ForeignKey(Laptop)      
    def __unicode__(self):
        return self.ordernum

class Openstack_Auth(models.Model):
    os_url = models.URLField(max_length=200)
    os_project_domain_name = models.CharField(max_length=100)
    os_user_domain_name = models.CharField(max_length=100)
    os_tenant_name = models.CharField(max_length=100)
    os_project_name = models.CharField(max_length=100)
    os_user_name = models.CharField(max_length=100)
    os_password = models.CharField(max_length=100)
    os_password_encrypt = EncryptedCharField(max_length=100, null=True)
    os_url_type = models.CharField(max_length=20, default='publicURL')
    os_stack_id = models.CharField(max_length=100, null=True)

djproject/simpleapp1/forms.py
'''
Created on Jul 24, 2016

@author: bhujay
'''

from django import forms
from django.forms import  ModelForm, formset_factory
from django.forms import Textarea,CheckboxInput,SelectMultiple ,PasswordInput
from simpleapp1.models import Laptop,Order,Openstack_Auth
from django.forms.widgets import NumberInput


class LaptopForm(ModelForm):
    selected = forms.BooleanField(label = 'Select', required=False)
    class Meta:
        model=Laptop
        fields='__all__'
        #exclude = ['os']
        
class OrderForm(ModelForm):
    #selected = forms.BooleanField(label = 'Select', required=False)
    class Meta:
        model=Order        
        fields= ['laptop', 'qty']
        widgets = {
            'qty': NumberInput(attrs={'size':20}),
        }
class OSAuthEditForm(ModelForm):
    #os_password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model=Openstack_Auth        
        fields='__all__'
        exclude = ['os_password']
        widgets = {
            'os_password_encrypt': PasswordInput(),
            }

       
        

djproject/simpleapp1/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from __future__ import print_function
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.shortcuts import render
import socket

import subprocess
from subprocess import  PIPE
from multiprocessing import Pool
from multiprocessing import cpu_count
import psutil
import time
from django.template.defaultfilters import join

from simpleapp1.forms import LaptopForm, OrderForm
from models import Laptop, Order, Openstack_Auth
from django.forms import formset_factory,modelformset_factory,inlineformset_factory


from keystoneauth1 import loading , session
from novaclient import client as novaclient
from gnocchiclient import client as gclient
from aodhclient.v2 import client as aclient
import datetime


from django.views.generic import ListView , DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
import forms

from simpleapp1.openstack_graph_module import openstack_graph_func


process_pid_list = []

def index(request):  
    laptop_all = Laptop.objects.all()
    order_all = Order.objects.all()  
    if request.method == 'POST':
        order_form = OrderForm(request.POST)
        if order_form.is_valid():
            lapdop_data = order_form.cleaned_data['laptop']
            laptop_object = Laptop.objects.get(laptopmodel = lapdop_data )
            laptop_id = laptop_object.id
            current_stock = int(laptop_object.currentstock)
            order_qty = int(order_form.cleaned_data['qty'])
            
            if  order_qty <= current_stock:
                updated_stock = current_stock-order_qty
                try:
                    laptop_object.currentstock = updated_stock
                    laptop_object.save()
                    order_rec = Order(laptop=laptop_object, qty=order_qty)
                    order_rec.save()
                    order_number = order_rec.id
                except django.db.Error as e:
                    print (str(e))
                    
                msg = (' %s number of %s Laptop Order has been Booked.Your Order Number is : - %s. Updated  available stock is %s '
                       % (str(order_qty),
                            lapdop_data,
                            str(order_number),
                            str(updated_stock)
                                                                
                         ) 
                      )
            else:
                 msg = ("%s  numbers of %s Laptop are not available in stock, Try different model or reduce quantity below %s" 
                         % (str(order_qty),
                            lapdop_data,
                            str(current_stock)                                    
                                   ) 
                         )                 
            context = {'laptop_all': laptop_all, 'order_all': order_all, 'msg': msg,
                       'hostname': socket.gethostname(), 
                       'ipaddr': socket.gethostbyname(socket.gethostname()) , 
                       'cpu_util': psutil.cpu_percent(),}
            #return HttpResponse(msg)
            return render(request,'business.html', context)                                    
                                
    else:
        order_form = OrderForm()
    context = {'order_form': order_form,'laptop_all': laptop_all, 'order_all': order_all,
               'hostname': socket.gethostname(), 
               'ipaddr': socket.gethostbyname(socket.gethostname()) , 
               'cpu_util': psutil.cpu_percent(),}
    return render(request,'business.html', context)

def f(x):
    while True:
        x*x

def overload_cpu(request):
    hostname = socket.gethostname()
    ipaddr = socket.gethostbyname(hostname)
#    processes = cpu_count()
#     print('utilizing %s cores:' % str(processes))
#     print(psutil.cpu_percent())
#     pool = Pool(processes)
#     pool.map(f(1000), range(processes))
    #proc = subprocess.Popen(['/bin/sh', '/home/bhujay/x.sh'], stdout=PIPE, stderr=PIPE)
    #proc = subprocess.Popen(['cat', '/dev/zero', '>', '/dev/null'])
    proc = subprocess.Popen(['dd', 'if=/dev/zero', 'of=/dev/null'])
    process_pid_list.append(proc.pid)    
    context = {'hostname': hostname, 
               'ipaddr': ipaddr ,
               'cpu_core': cpu_count(), 
               'cpu_util': psutil.cpu_percent(), 
               'process_pid_list': process_pid_list}
    return render(request, 'overload_cpu.html', context )
    #return HttpResponse("Will slap you ")
#
def kill_load(request, procid):
    hostname = socket.gethostname()
    ipaddr = socket.gethostbyname(hostname)
    p = subprocess.Popen(["kill", "-9",  procid]) 
    
    try:
        process_pid_list.remove(int(procid))
    except:
        pass
    
    context = {'hostname': hostname, 
               'ipaddr': ipaddr ,
               'cpu_core': cpu_count(), 
               'cpu_util': psutil.cpu_percent(), 
               'process_pid_list': process_pid_list}
    return render(request, 'killed_process.html', context )
    #return HttpResponse(l)

# openstack minitoring view 
def openstack_view(request):
    try:
        conf=Openstack_Auth.objects.get(pk=1)
        loader = loading.get_plugin_loader('password')
        auth = loader.load_from_options(auth_url= conf.os_url,
                                     project_domain_name= conf.os_project_domain_name,
                                     user_domain_name=  conf.os_user_domain_name,
                                     username=  conf.os_user_name,
                                     #password= conf.os_password,
                                     password= conf.os_password_encrypt,
                                     tenant_name= conf.os_tenant_name,
                                     project_name= conf.os_project_name, 
                                     )
        sess = session.Session(auth=auth)
        nova = novaclient.Client('2', session=sess,endpoint_type= conf.os_url_type)
        gcon = gclient.Client('1', session=sess,
                           adapter_options={'connect_retries': 3,
                           'interface': conf.os_url_type} )
        al = nova.servers.list()
        slist = []
        td = datetime.timedelta(hours=5, minutes=30)
        for s in al:
            xlist = []    
            if 'asg_name' in s.metadata and s.metadata['asg_name']=='autoscale_demo_1':
                try:
                    #Gnocchi data collection for the server s 
                    all_cpu_util_values=gcon.metric.get_measures('cpu_util',resource_id=s.id)     
                    vdate, vgran, cutil = all_cpu_util_values[-1]
                    vdatef = vdate.strftime('%Y-%m-%d %H:%M:%S')
                    for cpu_util_value in all_cpu_util_values:
                       udate, xgran, xutil = cpu_util_value
                       xdate = udate+td
                       xdict = {'xdate': xdate.strftime('%Y-%m-%d %H:%M:%S'), 'xutil': xutil}
                       xlist.append(xdict)
                except:
                    all_cpu_util_values = []
                    vdatef, vgran, cutil = ('try after 10 Minutes', 'try after 10 Minutes', 'try after 10 Minutes')
                    xlist = []
                    
                try:
                    list_of_ips=s.networks.itervalues().next()
                    fixedip=list_of_ips[0]
                    floatip=list_of_ips[1]
                except:
                    fixedip='getting prepared'
                    floatip='getting prepared'
                    
                #Create the various key value parameters for server s
                sdict = {'sobj': s, 'fixedip': fixedip, 'floatip': floatip, 
                  'collection_time' : vdatef, 'cutil': cutil,
                  'all_cpu_util_values': all_cpu_util_values,
                  'xlist': xlist }
                #add all the servers key value in a list for template to unpack 
                slist.append(sdict)  
                
    except:
        pass
    alist = []
    ahistory_with_localtime = []
    td = datetime.timedelta(hours=5, minutes=30)
    try:
        acon =  aclient.Client(session=sess,interface= 'internalURL')
        for myalarm in acon.alarm.list():
           rule=myalarm['gnocchi_aggregation_by_resources_threshold_rule']
           rq=rule['query']
           #if 'f447c07f-ff7b-48b8-924b-ff7220e20c0b' in rq:
           if conf.os_stack_id in rq:
               aid = myalarm['alarm_id']
               aname = myalarm['name']
               ahistory_with_utc = acon.alarm_history.get(aid)
               for h in ahistory_with_utc:
                   htime = datetime.datetime.strptime(h['timestamp'], '%Y-%m-%dT%H:%M:%S.%f')
                   htime_local = htime+td
                   ht_str = htime_local.strftime('%Y-%m-%dT%H:%M:%S.%f')
                   ahistory_with_localtime.append({'timestamp': ht_str, 'detail': h['detail']})
               adict = {'aid': aid, 'aname': aname, 'ahistory': ahistory_with_localtime }
               alist.append(adict)
    except:
        pass
    context = {'slist': slist, 'alist': alist}
    return render(request, 'openstack_view.html', context)

def openstack_graph_view(request):
    context = openstack_graph_func()
    return render(request, 'openstack_graph_template.html', context)
   
# Iventory addition and update by the store manager
class Inventory(ListView):
    model = Laptop
    template_name = 'inventory.html'
    
class InventoryAdd(CreateView):
    model = Laptop
    fields = ['laptopmodel', 'currentstock']
    template_name = 'InventoryAdd.html'
    success_url = reverse_lazy('simpleapp1:inventory')
    
class InventoryUpdate(UpdateView):
    model = Laptop
    fields = ['laptopmodel', 'currentstock']
    template_name = 'InventoryUpdate.html'

djproject/simpleapp1/templates/InventoryAdd.html
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add" />
</form>

djproject/simpleapp1/templates/killed_process.html
<h1> Process ID : {{ process_pid }} has been Killed , refresh the page to  watch CPU utilization coming down </h1>

<table >
<tr> 
<td>
	<p> Hostname  </p> 
</td>
<td>
	<p> {{ hostname }} </p> 
</td>
</tr> 
<tr> 
<td>
	<p> IP address  </p> 
</td>
<td>
	<p> {{ ipaddr }} </p> 
</td>
</tr> 

<tr> 
<td>
	<p> CPU Core USed   </p> 
</td>
<td>
	<p> {{ cpu_core }} </p> 
</td>
</tr> 
<tr> 
<td>
	<p> CPU Utilization in %  </p> 
</td>
<td>
	<p> {{ cpu_util }} </p> 
</td>
</tr> 
<tr> 
<td>
	<p> Current CPU Utilization  </p> 
</td>
<td>
	<p> {{ cpu_util }} </p> 
</td>
</tr> 
{% for process_pid in process_pid_list %}
<tr> 
<td>
	<p> CPU Load Process PID that is still running  </p> 
</td>
<td>
	<p> <a href="{% url 'simpleapp1:kill_load' process_pid  %}" > {{ process_pid }} click here to kill   </a> </p> 
</td>
<tr>
{% endfor %}
</table>
<br>
<a href= "{% url 'simpleapp1:index'  %}"> Go to Home page</a> <br>
<a href= "{% url 'simpleapp1:openstack'  %}"> View Openstack Monitoring</a><br>
<a href= "{% url 'simpleapp1:openstackgraph'  %}"> Switch to Graphical Monitoring View</a>


<style>
   
   table {font-size:8pt;width:100%;color:blue;border:0px solid black;}
   td  {border:1px solid black;}
   input {width:50;color:blue;font-size:8pt;width:60px}
    .div-left{
    float:left;
    padding-left:10px;
    margin-left:20px
}
.div-right{
    float:right;
    padding-right:10px;
    margin-right:100px
}
.container{
     
    max-width:100%;
    border:1px solid salmon;
    
    padding-top:5px;
}

.td-log {width:90%

}
   </style>

djproject/simpleapp1/templates/openstack_graph_template.html
{% load i18n %}
{% load l10n %}
{% load static %}

<!doctype html> 
<html>
<head>
<script src='{% static "simpleapp1/cloudkitty/js/d3.min.js" %}' type='text/javascript' charset='utf-8'></script>
<script src='{% static "simpleapp1/cloudkitty/js/rickshaw.min.js" %}' type='text/javascript' charset='utf-8'></script>
<script src='{% static "simpleapp1/cloudkitty/js/moment.js" %}' type='text/javascript' charset='utf-8'></script>
<script src='{% static "simpleapp1/cloudkitty/js/moment-with-locales.js" %}' type='text/javascript' charset='utf-8'></script>
<link href='{% static "simpleapp1/rickshaw/rickshaw.min.css" %}' type='text/css'  rel='stylesheet'>

<style>   
table {font-size:8pt;width:100%;color:blue;border:0px solid black;}
td  {border:1px solid black;}  
input {width:50;color:blue;font-size:8pt;width:60px}   
.div-left{
    float:left;
    padding-left:2px;
    margin-left:2px
}
.div-right{
    float:right;
    padding-right:2px;
    margin-right:2px
}
.container{     
    max-width:100%;
    border:1px solid salmon;    
    padding-top:5px;
}

.td-log {width:90%
}
</style>

</head>

<body>
<a href= "{% url 'simpleapp1:index'  %}"> Go to Home page</a> &nbsp 
<a href= "{% url 'simpleapp1:osauth'  %}"> Click to  Enter Openstack authentication information here</a> &nbsp
<a href= "{% url 'simpleapp1:openstack'  %}"> Switch to Openstack Monitoring Text View</a>
<div id="container">
	<div class="col-md-6" style="width:610px; float:left;">
	<h4>{% trans "cpu utilization per 5 minute per server" %}</h4>
	<div id="cpu_utilization"  ></div>
	<div id="cpu_utilization_legend" ></div>
	</div>
	<div id="alarm-area" style="width:590px; float:right;">
	    <table>
	    <tr>
	    <td>
	    <figure style="width:80px">
		<img id="cpuhigh" src="{% static 'simpleapp1/pics/pic_bulboff.gif' %}" style="width:80px"/>
		<figcaption>CPU High Alarm</figcaption>
		</figure>	
                       <script>
            		{% for a in alist %}
  				{% if 'high'  in a.aname %}
     					{% if 'alarm' in  a.ahistory.0.detail %}
        					document.getElementById('cpuhigh').src="/static/simpleapp1/pics/pic_bulbon.gif";
     					{% endif %}
   				{% endif %}
			{% endfor %}
		       </script>

	    </td>	    
	    <td>	    		
		<figure style="width:80px">
		<img id="cpulow" src="{% static 'simpleapp1/pics/pic_bulboff.gif' %}" style="width:80px"/>	
		<figcaption>CPU Low Alarm </figcaption>
		</figure>
                     <script>
                        {% for a in alist %}
                                {% if 'low'  in a.aname %}
                                        {% if 'alarm' in  a.ahistory.0.detail %}
                                                document.getElementById('cpulow').src="/static/simpleapp1/pics/pic_bulbon.gif";
                                        {% endif %}
                                {% endif %}
                        {% endfor %}
                       </script>

	    </td>
	    </tr>
	    </table>		
	</div>
</div>
<script> 
//var unit_formatter = {name: '5 hour', seconds: 3600 * 5, formatter: (d) -> moment(d).format('h:mm a')};
var palette = new Rickshaw.Color.Palette();
var graph = new Rickshaw.Graph({
  element: document.querySelector('#cpu_utilization'),
  width: 600,
  height: 200,
  renderer: 'line',
  interpolation: 'linear',
  onComplete: function(w) {
    var legend = new Rickshaw.Graph.Legend({
      element: document.querySelector('#cpu_utilization_legend'),
      graph: w.graph
    });
  },
  series: [
	  {% for s in slist %}
	      {
	        color: palette.color(),
	        //name: "{{ slist.0.fixedip }},cpu: - ",
	        name: "{{ s.fixedip }},cpu: - ",
	        data: [
	        {% for d in s.xlist|slice:"-60:"  %} {x: {{ d.xdate }}, y: {{ d.xutil }}}, {% endfor %}
	        //{% for d in slist.0.xlist|slice:"-60:"  %} {x: {{ d.xdate }}, y: {{ d.xutil }}}, {% endfor %}
	        ]
	      },
	  {% endfor %}
	    ]
});
graph.render();
 
var hoverDetail = new Rickshaw.Graph.HoverDetail( { 
		    graph: graph,
		    xFormatter: function(x) {
                return new Date( x * 1000 ).toLocaleString();
                    }

} );
		
var yAxis = new Rickshaw.Graph.Axis.Y({
		    graph: graph,
});
yAxis.render();

var xAxis = new Rickshaw.Graph.Axis.Time({
		    graph: graph,
		    timeFixture: new Rickshaw.Fixtures.Time.Local()

});
xAxis.render();
</script> 

<br>
<table >
<th>Hostname</th>  <th>HostID</th><th>Launched  at</th> 
<th> Fixed IP</th> <th> Float IP </th>
<th> CPU Util data (UTC )</th> 
{% for s in slist %}
<tr> 
    <td> {{ s.sobj.name }} </td>   <td> {{ s.sobj.id }} </td><td>{{ s.sobj.created}}</td>  <td>{{ s.fixedip }}</td>
    <td> <a href= "http://{{ s.floatip }}/autoscale " > {{ s.floatip }} </a> </td>
    <!--td>{{ s.collection_time }}</td> <td>{{ s.cutil }}</td-->
    <td>
       <table>
       {% for d in s.xlist|slice:"-3:" %}
         	<tr>
	    	 <td> {{d.xutil}} </td>
   	        </tr>  
       {% endfor %}
     </table>
    </td>
{% endfor %}
</tr>
</table>


<p> Scroll down to see the Alarm status for high cpu and low cpu threshold. When the state is transitioned to alarm the action to scaleup or scale
down is triggerred </p>

<br>
<table>
{% for a in alist %}
<th> {{ a.aname }}</th> <th> Alarm State </th>
{% for h in a.ahistory %}
<tr><td> {{ h.timestamp }} </td> <td> {{ h.detail }} </td> </tr>
{% endfor %}
{% endfor %}
</table>

{% for a in alist %}  
  {% if 'high'  in a.aname %}
     {{ a.ahistory.0.detail }}
     {% if 'alarm' in  a.ahistory.0.detail %}
       <p> Alarm is ON </p>
        document.getElementById('cpuhigh').src="{% static 'simpleapp1/pics/pic_bulboff.gif' %}";
     {% endif %}
   {% endif %}
{% endfor %}

</body>


</html>


<!--
<br>
<div class="container">

<div class="div-left">
<table>
<th> {{ alist.0.aname }} </th>  <th>Alarm Details</th>
 {% for h in alist.0.ahistory %}
<tr><td> {{ h.timestamp }} </td> <td> {{ h.detail }} </td> </tr>
{% endfor %}
</table>
</div>

<div class="div-right">
<table>
<th> {{ alist.1.aname }} </th>  <th>Alarm Details</th>
 {% for h in alist.1.ahistory %}
<tr><td> {{ h.timestamp }} </td> <td> {{ h.detail }} </td> </tr>
{% endfor %}
</table>
</div>

</div>
-->

djproject/simpleapp1/templates/osauth.html
 
<h2> Authentication information for your openstack cloud project</h2>
<ul>
<li>url os the keystone in the form of https://10.172.124.14:5000/v3 or http://10.172.100.14:5000/v3</li>
<li>From your VM  one of the above IP should be reachable and accordingly the url type need to be set as 
publicURL or internalURL</li>
<li>tenant name and project name is same </li>
<li> project domain name and user domain name is same  </li>
</ul>

    <h2>Openstack Authentication Details , only the first record with id= 1 is valid entry</h2>
    <table>
    <th> id></th>  <th> keystone url</th> <th> domain> </th> <th> u domain</th> <th> tenant </th>
    <th> project </th> <th> user name </th> <th> endpoit type </th> <th> stack id </th>
        {% for osauth in object_list %}
         <tr> 
            <td> {{ osauth.id }}</td>
             <td> {{ osauth.os_url }} </td>
              <td> {{ osauth.os_project_domain_name }} </td>
               <td>{{ osauth.os_user_domain_name }}</td>
          <td>{{ osauth.os_tenant_name }}</td>
               <td>{{ osauth.os_project_name }}</td>
               <td>{{ osauth.os_user_name }}</td>
               <td>{{ osauth.os_url_type }}</td>
               <td>{{ osauth.os_stack_id }}</td>
               <td><a href = "{% url 'simpleapp1:osauth_update' osauth.id %}" > Edit Authentication Detail {{ laptop.id  }}</a></td>
            </tr> 
        {% endfor %}
    </table>
  <br>
  <a href= "{% url 'simpleapp1:osauth_add'%}"> Click to  Enter Openstack authentication information here</a><br>
  <a href= "{% url 'simpleapp1:openstack'%}"> Click to  view openstack monitoring data</a>

    
    

    

djproject/simpleapp1/templates/overload_cpu.html
<h1> CPU load has been generated , and the current utilizatuion is as follows </h1>

<table >
<tr> 
<td>
	<p> Hostname  </p> 
</td>
<td>
	<p> {{ hostname }} </p> 
</td>
</tr> 
<tr> 
<td>
	<p> IP address  </p> 
</td>
<td>
	<p> {{ ipaddr }} </p> 
</td>
</tr> 

<tr> 
<td>
	<p> CPU Core USed   </p> 
</td>
<td>
	<p> {{ cpu_core }} </p> 
</td>
</tr> 
<tr> 
<td>
	<p> CPU Utilization in %  </p> 
</td>
<td>
	<p> {{ cpu_util }} </p> 
</td>
</tr> 
<tr> 
<td>
	<p> Current CPU Utilization  </p> 
</td>
<td>
	<p> {{ cpu_util }} </p> 
</td>
</tr> 
{% for process_pid in process_pid_list %}
<tr> 
<td>
	<p> Process PID   </p> 
</td>
<td>
	<p> <a href="{% url 'simpleapp1:kill_load' process_pid  %}" > {{ process_pid }} Click here to kill this cpuload process </a> </p> 
</td>
<tr>
{% endfor %}
<td>

</td>
</tr>
</tr> 
</table>
<br>
<a href= "{% url 'simpleapp1:index'  %}"> Go to Home page</a> <br>
<a href= "{% url 'simpleapp1:openstack'  %}"> View Openstack Monitoring</a><br>
<a href= "{% url 'simpleapp1:openstackgraph'  %}"> Switch to Graphical Monitoring View</a>


<style>
   
   table {font-size:8pt;width:100%;color:blue;border:0px solid black;}
   td  {border:1px solid black;}
   input {width:50;color:blue;font-size:8pt;width:60px}
    .div-left{
    float:left;
    padding-left:10px;
    margin-left:20px
}
.div-right{
    float:right;
    padding-right:10px;
    margin-right:100px
}
.container{
     
    max-width:100%;
    border:1px solid salmon;
    
    padding-top:5px;
}

.td-log {width:90%

}
   </style>

djproject/simpleapp1/templates/server_stat.html
<h4>Server Informatiom and CPU load </h4>
<table >
<div class = "table">

<tr> <td><p> Hostname</p></td>   <td><p> {{ hostname }} </p></td> </tr> 
<tr> <td><p>IP address</p></td>  <td><p> {{ ipaddr }} </p></td> </tr> 
<tr> <td><p> Current CPU Utilization  </p> </td>  <td><p> {{ cpu_util }} </p></td></tr> 
<tr> <td> Load Generator</td> <td><a href="cpuload/">To generate load on CPU  - click here</a></td></tr>
</table>
<br>
<a href= "{% url 'simpleapp1:osauth'  %}"> configure settings to view openstack monitoring  </a> <br>
<a href= "{% url 'simpleapp1:openstack'  %}"> See  server utilization from openstack  cloud monitoring view </a><br>
<a href= "{% url 'simpleapp1:openstackgraph'  %}"> Switch to Graphical Monitoring View</a>
</div>



<style>
   
   table {font-size:8pt;width:100%;color:blue;border:0px solid black;}
   td  {border:1px solid black;}
   input {width:50;color:blue;font-size:8pt;width:60px}
    .div-left{
    float:left;
    padding-left:10px;
    margin-left:20px
}
.div-right{
    float:right;
    padding-right:10px;
    margin-right:100px
}
.container{
     
    max-width:100%;
    border:1px solid salmon;
    
    padding-top:5px;
}

.td-log {width:90%

}
   </style>